### ISSUE TITLE
Bug in large number conversion

### ISSUE THREAD

**Issue by nyurik** [Skalman/baseconvert-ui#1] opened 2015-09-09 03:46 UTC
Using http://baseconvert.com/ I noticed that base 16 - fffffffffffff converts to a binary with all 1s, but adding just one more "f" makes the binary 10000..., which is clearly an error.

**Comment by Skalman** [comment] 2015-09-09 05:55
JavaScript supports 53 bits of precision, and that extra "f" passes that threshold. Therefor rounding takes place.
The solution to this is to use arbitrary precision numbers in the calculations, but I haven't found any good arbitrary precision floating point libraries for JavaScript.

Another, easier but not complete, solution could be to implement special cases for bases 2/8/16, to support arbitrary precision for conversions between them. I'm hesitant to adding this, because it would suggest greater precision in other conversions too.

**Comment by Skalman** [comment] 2015-09-09 05:56
Duplicate of https://github.com/Skalman/baseconvert/issues/3.

**Closed by Skalman** 2015-09-09 05:56 UTC
Labels: duplicate

**Comment by nyurik** [comment] 2015-09-09 17:23
Take a look at http://convertxy.com/index.php/numberbases/  -- it works fine there

**Comment by Skalman** [comment] 2015-09-09 17:51
It does. It also uses an implementation in PHP (likely using [BC Math](http://php.net/bc)), not JavaScript. I don't intend to implement a PHP version, but I'd be open to merging a pull request with an implementation, as long as it uses JavaScript for the cases that it can handle, and also doesn't mess up the application cache.

**Comment by Skalman** [comment] 2015-12-30 01:12
@nyurik, I found the excellent [big.js](https://github.com/MikeMcl/big.js), which supports arbitrarily big integers, and also has better fractional precision than JS natively. I've integrated that library, so now you will see the correct result for converting e.g. "fffffffffffff" from base 16 to base 10. Fixed in 46bfb0fada4eafb59f21bdeadff6ef5d4d10d8bb.

**Comment by nyurik** [comment] 2015-12-30 01:17
Awesome, thanks!  Did you update the site?  Because I tried typing very large numbers in, and they begin showing zeroes at the end at some point.

**Comment by Skalman** [comment] 2015-12-30 07:31
I did update the site, though it seems like at least Firefox has a bug where it won't update the offline version (I used the appcache to be able to use the site while offline). If you're using Firefox, you can clear the cache by going to Preferences>Advanced>Network and remove the offline web content for baseconvert.com.
For now, I've removed offline support, though I might re-add it using service workers at some point.
